name = "steam-n-punk-kingdom"
author = "STANN.co"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "069763f9d17c84e54865a306d0ecbaa6b1e8ceac1c974c4f5e0f947aac81cce3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
