name = "steam-n-punk-kingdom"
author = "STANN.co"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "818d6258e550079475220b8b7a9eca62449e50f81004c5d926d00e6a13a80130"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
