name = "steam-n-punk-kingdom"
author = "STANN.co"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "091e6bbf1f72d37152512284e36e49e4f955ce1d6a004a056038679d641840d3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
